print("Welcome to the tip calculator!")
total_bill=float(input("What was the total bill? $"))
tip_percent=float(input("What percentage tip would you like to give? "))
people=int(input("How many people to split the bill? "))
formatted_answer="{:.{}f}".format(total_bill * (1+tip_percent/100) / people, 2)
print(f"Each person should pay: ${formatted_answer}")